### ISSUE TITLE
Shows border in some cases irregularly

### ISSUE THREAD

**Issue by tranjeeshan** [snwh/yuyo-gtk-theme#8] opened 2014-12-12 12:41 UTC
I know this theme is not yet a finished project. I've found some bugs which needs to be fixed for a consistent feel. I don't know what is the name of the bar under any menu which indicates the selected menu, but there're some irregularity in them. Like, it works well with most of them windows except dialog boxes and 'help documentation window'. I've attached screenshot of correctly implemented windows, and two samples of wrong behaviored theming. They don't seem to work correctly. One of them shows menu border which isn't intended behavior for this Yuyo theme, as I figured. Another one shows colored background instead of underline (or, below bar) as intended. 
I hope these and more other minor issues would be fixed for a consistent feel in Yuyo.
![need_to_be_fixed](https://cloud.githubusercontent.com/assets/2022469/5411752/7f99dade-822e-11e4-818a-51e514c90ff8.png)
![need_to_be_fixed_2](https://cloud.githubusercontent.com/assets/2022469/5411751/7f91db54-822e-11e4-81f7-ae1b660cbb15.png)
![sample_screenshot](https://cloud.githubusercontent.com/assets/2022469/5411750/7f892d88-822e-11e4-9565-22c427f0635b.png)

**Comment by snwh** [comment] 2015-02-07 06:12
Hmm, this is also due to the lack of shadows on menus with the desktop effects disabled.

**Comment by flexiondotorg** [comment] 2015-02-13 02:32
Duplicate of #11

**Closed** 2015-02-13 02:32 UTC
Labels: confirmed
