### ISSUE TITLE
More "traditional" look for active tab?

### ISSUE THREAD

**Issue by nadrimajstor** [snwh/yuyo-gtk-theme#12] opened 2014-12-15 12:21 UTC
Example:
![yuyo-dark_active_tab_look2](https://cloud.githubusercontent.com/assets/1753467/5435618/0378e612-845d-11e4-9d0b-ed91cd287606.png)

**Comment by flexiondotorg** [comment] 2015-02-13 02:30
Duplicate of #11

**Closed by flexiondotorg** 2015-02-13 02:30 UTC
